services:
  - type: web
    name: quanlykhohang
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb://127.0.0.1:27017/quanlykhohang
      - key: JWT_SECRET
        value: your_secret_key_here 